---
- name: Ensure httpd Latest Release Installed
  yum: name=httpd state=latest
  become: yes

- name: Ensure httpd Service Running and Enabled
  service: name=httpd state=started enabled=yes
  become: yes

- name: Cp vhost conf
  template:
    src: "/home/student/repositories/Ansible/day2/roles/httpd/templates/vhost.conf.j2"
    dest: "/etc/httpd/conf.d/vhost.conf"
  notify: Restart service httpd
  become: yes

- name: Get httpd Version
  shell: /usr/sbin/httpd -v 2>&1 | awk -F'/' '{print $2}'
  register: httpd_version


# tasks file for httpd