---
- name: save httpd details
  copy:
    content: >
      {
        "version": "{{ httpd_version.stdout }}",
        "repository": {
          "file": "/etc/yum.repos.d/httpd.repo",
          "name": "httpd/{{ ansible_distribution_major_version }}/{{ ansible_userspace_architecture }}",
          "description": "httpd Centos Repo"
        },
        "configuration": {
          "TLS": "{{ httpd_tls.stdout }}",
          "configure_arguments": {{ httpd_configure_arguments.stdout_lines }}
        },
        "installed": "{{ ansible_date_time.iso8601 }}"
      }
    dest: /etc/ansible/facts.d/httpd.fact
  become: yes
# handlers file for httpd

- name: Restart service httpd
  service:
    name: httpd
    state: restarted
  become: yes