- hosts: localhost

  tasks:

  - name: Check if Tomcat Responds 200
    shell: curl -sL -w "%200" localhost:8080 -o /dev/null | grep 200
    args:
      warn: false

  - name: Check if It's really Tomcat
    shell: curl -s localhost:8080 | grep '<title>Apache Tomcat' >/dev/null
    args:
      warn: false