---
#tomcat_release: "8.5.43"
tomcat_user: tomcat
tomcat_group: "{{tomcat_user}}"
tomcat_user_id: 950
tomcat_group_id: 950
tomcat_home: /opt/apache/tomcat

tomcat_admin_enabled: false
tomcat_admin: admin
tomcat_admin_password: "{{ lookup('password', '/dev/null length=15 chars=ascii_letters') }}"
tomcat_url: "http://www-eu.apache.org/dist/tomcat/tomcat-{{ tomcat_release.split('.')[0] }}/v{{ tomcat_release }}/bin/apache-tomcat-{{ tomcat_release }}.tar.gz"
tomcat_java_version: "1.{{ tomcat_release.split('.')[0] }}.0"
